create_clock -period 10.000 -name CLK -waveform {0.000 5.000} [get_ports clk]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U16 [get_ports {gpioPorts[0]}]
set_property PACKAGE_PIN E19 [get_ports {gpioPorts[1]}]
set_property PACKAGE_PIN U19 [get_ports {gpioPorts[2]}]
set_property PACKAGE_PIN V19 [get_ports {gpioPorts[3]}]
set_property PACKAGE_PIN W18 [get_ports {gpioPorts[4]}]
set_property PACKAGE_PIN U15 [get_ports {gpioPorts[5]}]
set_property PACKAGE_PIN U14 [get_ports {gpioPorts[6]}]
set_property PACKAGE_PIN V14 [get_ports {gpioPorts[7]}]
set_property PACKAGE_PIN W19 [get_ports {gpioPorts[8]}]
set_property PACKAGE_PIN U18 [get_ports {gpioPorts[9]}]
set_property PACKAGE_PIN T17 [get_ports {gpioPorts[10]}]
set_property PACKAGE_PIN U3 [get_ports {gpioPorts[11]}]
set_property PACKAGE_PIN P3 [get_ports {gpioPorts[12]}]
set_property PACKAGE_PIN N3 [get_ports {gpioPorts[13]}]
set_property PACKAGE_PIN P1 [get_ports {gpioPorts[14]}]
set_property PACKAGE_PIN L1 [get_ports {gpioPorts[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpioPorts[0]}]

set_property DRIVE 12 [get_ports {gpioPorts[15]}]
set_property DRIVE 12 [get_ports {gpioPorts[14]}]
set_property DRIVE 12 [get_ports {gpioPorts[13]}]
set_property DRIVE 12 [get_ports {gpioPorts[12]}]
set_property DRIVE 12 [get_ports {gpioPorts[11]}]
set_property DRIVE 12 [get_ports {gpioPorts[10]}]
set_property DRIVE 12 [get_ports {gpioPorts[9]}]
set_property DRIVE 12 [get_ports {gpioPorts[8]}]
set_property DRIVE 12 [get_ports {gpioPorts[7]}]
set_property DRIVE 12 [get_ports {gpioPorts[6]}]
set_property DRIVE 12 [get_ports {gpioPorts[5]}]
set_property DRIVE 12 [get_ports {gpioPorts[4]}]
set_property DRIVE 12 [get_ports {gpioPorts[3]}]
set_property DRIVE 12 [get_ports {gpioPorts[2]}]
set_property DRIVE 12 [get_ports {gpioPorts[1]}]
set_property DRIVE 12 [get_ports {gpioPorts[0]}]

set_property SLEW SLOW [get_ports {gpioPorts[15]}]
set_property SLEW SLOW [get_ports {gpioPorts[14]}]
set_property SLEW SLOW [get_ports {gpioPorts[13]}]
set_property SLEW SLOW [get_ports {gpioPorts[12]}]
set_property SLEW SLOW [get_ports {gpioPorts[11]}]
set_property SLEW SLOW [get_ports {gpioPorts[10]}]
set_property SLEW SLOW [get_ports {gpioPorts[9]}]
set_property SLEW SLOW [get_ports {gpioPorts[8]}]
set_property SLEW SLOW [get_ports {gpioPorts[7]}]
set_property SLEW SLOW [get_ports {gpioPorts[6]}]
set_property SLEW SLOW [get_ports {gpioPorts[5]}]
set_property SLEW SLOW [get_ports {gpioPorts[4]}]
set_property SLEW SLOW [get_ports {gpioPorts[3]}]
set_property SLEW SLOW [get_ports {gpioPorts[2]}]
set_property SLEW SLOW [get_ports {gpioPorts[1]}]
set_property SLEW SLOW [get_ports {gpioPorts[0]}]

set_property PACKAGE_PIN T18 [get_ports reset]

