set_property PACKAGE_PIN W5 [get_ports sysClk]
set_property PACKAGE_PIN U18 [get_ports sysRes]
set_property IOSTANDARD LVCMOS33 [get_ports sysClk]
set_property IOSTANDARD LVCMOS33 [get_ports sysRes]


set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCdebug[16]}]
set_property PACKAGE_PIN L1 [get_ports {PCdebug[31]}]
set_property PACKAGE_PIN P1 [get_ports {PCdebug[30]}]
set_property PACKAGE_PIN N3 [get_ports {PCdebug[29]}]
set_property PACKAGE_PIN P3 [get_ports {PCdebug[28]}]
set_property PACKAGE_PIN U3 [get_ports {PCdebug[27]}]
set_property PACKAGE_PIN W3 [get_ports {PCdebug[26]}]
set_property PACKAGE_PIN V3 [get_ports {PCdebug[25]}]
set_property PACKAGE_PIN V13 [get_ports {PCdebug[24]}]
set_property PACKAGE_PIN V14 [get_ports {PCdebug[23]}]
set_property PACKAGE_PIN U14 [get_ports {PCdebug[22]}]
set_property PACKAGE_PIN U15 [get_ports {PCdebug[21]}]
set_property PACKAGE_PIN W18 [get_ports {PCdebug[20]}]
set_property PACKAGE_PIN V19 [get_ports {PCdebug[19]}]
set_property PACKAGE_PIN U19 [get_ports {PCdebug[18]}]
set_property PACKAGE_PIN E19 [get_ports {PCdebug[17]}]
set_property PACKAGE_PIN U16 [get_ports {PCdebug[16]}]
create_clock -period 20.000 -name CLK -waveform {0.000 10.000} [get_ports sysClk]

